### ISSUE TITLE
Missing `cryptoUtils.` prefix for computeHash in sampleAuthChangePassword

### ISSUE THREAD

**Issue by robbobfrh84** [danilop/AWS_Lambda_in_Action#13]
When going through this code with the book I noticed this little error in...
- chapter09/sampleAuth/fn/sampleAuthChangePassword (line ~76 & ~83).
- added `cryptoUtils.` to both computeHash functions and worked fine. 
- Big noob, sorry if I miss-took the issue.

**Comment by danilop** [comment]
Thanks, I fixed that!
