### ISSUE TITLE
Chapter 11 - cannot install

### ISSUE THREAD

**Issue by aniecki** [danilop/AWS_Lambda_in_Action#2]
Cannot install the program in the chapter 11 by running deploy script.

 It contains aws lambda update function - but where is the create function? Such function should be run first.

**Comment by danilop** [comment]
Hi, the idea of the media sharing app (as taken form the book) is to create and deploy the first version of the functions manually, using the provided code and the roles. This is important to understand all the available options. You can then use the deploy script for managing updates, that are more common.
