### ISSUE TITLE
need to change references to computeHash to cryptoUtils.computeHash

### ISSUE THREAD

**Issue by hyPagnIdqp** [danilop/AWS_Lambda_in_Action#3]
AWS_Lambda_in_Action/Chapter09/SampleAuth/fn/sampleAuthChangePassword/index.js

I got ReferenceError: computeHash is not defined at /var/task/index.js
until I changed to cryptoUtils.computeHash

**Comment by alejandro-2awesome** [comment]
Oh man... you saved my life. Any idea why this is happening?

**Comment by danilop** [comment]
Sorry for the delay, I fixed that.
